CREATE TABLE IF NOT EXISTS user_hint_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    problem_id INT NOT NULL,
    problem_title VARCHAR(255),
    problem_level VARCHAR(50),
    problem_tags TEXT,
    stage VARCHAR(30) NOT NULL,
    hint_level INT,
    question_type VARCHAR(30),
    button_id VARCHAR(80),
    question_text TEXT,
    submission_result VARCHAR(50),
    language VARCHAR(50),
    weakness_type VARCHAR(30),
    detected_intent VARCHAR(50),
    code_length INT,
    code_line_count INT,
    prompt_policy_version VARCHAR(30),
    selected_problem_fields TEXT,
    route VARCHAR(30),
    llm_provider VARCHAR(50),
    solved BOOLEAN,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_user_hint_log_user_created_at (user_id, created_at),
    INDEX idx_user_hint_log_weakness_type (weakness_type),
    CONSTRAINT fk_user_hint_log_user FOREIGN KEY (user_id) REFERENCES users (id)
);
